FROM ubuntu

RUN  apt-get -y update
RUN curl -sL https://deb.nodesource.com/setup_7.9
RUN  apt-get install -y nodejs

WORKDIR /home/site/wwwroot

COPY . /home/site/wwwroot


EXPOSE 80

CMD ["node", "index.js"]


